name: weather_test
description: A new Flutter project.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"


dependencies:
  flutter:
    sdk: flutter

  #Base
  logger: ^1.1.0

  #DI
  get_it: ^7.2.0

  #Model
  json_annotation: ^4.4.0
  freezed_annotation: ^1.1.0

  #Network
  dio: ^4.0.4
  retrofit: ^3.0.1+1

  #State Management
  flutter_bloc: ^8.0.1

  #UI
  easy_localization: ^3.0.0
  flutter_native_splash: ^2.1.2

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  build_runner: ^2.1.8
  json_serializable: ^6.1.5
  retrofit_generator: ^4.0.1
  freezed: ^1.1.1




flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/langs/


flutter_native_splash:
  color: "#57abd0"
  android_12:
  android: true
  ios: true
  #web: false
  fullscreen: true